### ISSUE TITLE
Wondering the actual usage of windows specific hid sensor device

### ISSUE THREAD

**Issue by eeyrw** [majbthrd/HIDsensor#1]
I've discovered hid sensor standard created by Microsoft for a long time. However I still wonder if there are some real and vivid product with hid sensor standard. Maybe some windows tablets equipped  sensors like ambient light sensor? But i think such kind sensor device has few chance to communicate through USB. Instead,  I2C or other more primitive bus are more common. So I think it seems more likely the experiment of Microsoft and few people actually use it.

**Comment by majbthrd** [comment]
As an example, a Dell Venue 7 Pro (Windows tablet) has the following HID Sensors:

Accelerometer, Orientation, Compass, Custom, Ambient Light, Gyrometer, and Inclinometer

You may not be aware that HID can be used across both USB and I2C.  This project implements USB.  A tablet with integrated sensors might use I2C.  Both appear to Windows as the same.

I wrote this project to demonstrate that additional USB HID Sensors can be created and added to a PC.  It is up to you to create such sensors if you are interested in making the effort.

A link to the HID Sensor specification (HUTRR39b) is already in the project README, and it provides a bevy of illustrative examples of sensor types.
