### ISSUE TITLE
About Visualisation in windows

### ISSUE THREAD

**Issue by mcSimoffa** [majbthrd/HIDsensor#2]
Hi !
I am trying your report descriptor with slight simplifications (input only). My device is enumerated correctly. It is located in the Sensors section. The driver is installed "The set of sensors Hid (version 2)".
Question: is there a standard windows application for viewing the incoming temperature data?

**Comment by majbthrd** [comment]
At the time that I developed this, I used a Microsoft program called "Sensor Diagnostic Tool".  It listed all sensors and could also show the current values from each.

Judging by this web page:

https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/the-sensor-diagnostic-tool

Microsoft now wants developers to now use something called "SensorExplorer".

Regardless, a web search for one or both of these should hopefully reveal more of the information that you are looking for.

P.S.: if the tools don't see your modified implementation, then you might want to make a backup and revert back to the original code.
